import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Make sure this imports your global styles including the new rule
import NavBar from "@/components/nav-bar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[1440px] w-full text-black px-7`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
